### ISSUE TITLE
Stage: Recommendation submission date dose not appearing  in LUP portal

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#1002]
Project Name: 52 nd Street Rezoning 

Actual Result: Recommendation submission date dose not appearing  in LUP portal
Expected result: Recommendation submission date should appear in LUP portal

![image](https://user-images.githubusercontent.com/57265341/69458253-ea666780-0d3c-11ea-99fa-aa549fc339a7.png)

**Comment by hannahkates** [comment]
RE: countdown question. The countdown is still displayed because the milestone hasn't been closed. In practice, LUR will close the milestones after they review the disposition that has been submitted. There are also cases where multiple CBs are assigned to the same project. One of them may submit early, while the others wait until the end of the review period. In those cases, it's appropriate for it to say the CB review is still the active milestone, since not all the CBs have finished their review.

**Comment by hannahkates** [comment]
Re: missing date. Several CB users are assigned to this project and not all of them have submitted their reviews yet. I think we should display the actual milestone end date instead, and only show it once the milestone is complete.

![image](https://user-images.githubusercontent.com/13967925/69550028-4e20a880-0f68-11ea-9d94-eca7cf1c378f.png)

**Comment by hannahkates** [comment]
This bug is resolved. QA Team please review.

**Comment by ksinghprod** [comment]
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/70087312-14901300-15e2-11ea-8276-433500dfd27d.png)
