### ISSUE TITLE
Update disposition recommendation options

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#1098]
ADO issue: https://dcp-paperless.visualstudio.com/dcp-paperless-dynamics/_queries/edit/10093/?triage=true
Should work on #1072 at the same time.

This likely involves both front-end and back-end work. In the API, we will need to figure out what the updated number codes are for these option sets.

**Changes being made in CRM:**
- [ ] Non-complying, Received After Clock Expired, vote quorum not present to be removed as option for Community Board recommendation option. 
- [ ] Received After Clock Expired to be removed from Borough President recommendation option set
- [ ] Non-Complying to be removed from option set of Borough Board Recommendation option set. 
- [ ] **Align recommendation option sets:**
  - [ ] **Borough President Recommendation field options to remain unchanged.** 
    - [ ] Favorable
    - [ ] Conditional Favorable 
    - [ ] Unfavorable
    - [ ] Conditional Unfavorable 
    - [ ] No Objection
    - [ ] Waiver of Recommendation
  - [ ] **Community Board Recommendation field Options to be modified as indicated below:** 
    - [ ] Approved change to 'Favorable'
    - [ ] Approved with modifications/Conditions change to 'Conditional Favorable'
    - [ ] Disapproved change to 'Unfavorable' 
    - [ ] Disapproved with Modifications/Conditions change to 'Conditional Unfavorable' 
    - [ ] No Objection - no change 
    - [ ] Waiver of Recommendation - no change
  - [ ] **Borough Board Recommendation field options:** 
    - [ ] Favorable - no change 
    - [ ] Unfavorable - no change 
    - [ ] Add the below options:
    - [ ] Conditional Favorable 
    - [ ] Conditional Unfavorable 
    - [ ] No Objection
    - [ ] Waiver of Recommendation

TODO: 

 - Resync metadata in Skyvia

**Comment by Eabrante** [comment]
Hi Hannah please see AB#10519 to user story details.

**Comment by godfreyyeung** [comment]
This is the new Option Set code mappings, from returned from test2 CRM Web Api on 3/13:

BP:
717170000 - Favorable 
717170001 - Conditional Favorable
717170002 - Unfavorable
717170003 - Conditional Unfavorable
717170005 - No Objection
717170006 - Waiver of Recommendation

BB: 
717170000 - Favorable
717170001 - Unfavorable
717170003 - Conditional Favorable
717170004 - Conditional Unfavorable
717170005 - No Objection
717170002 - Waiver of Recommendation

CB:
717170000 - Favorable
717170001 - Conditional Favorable
717170002 - Unfavorable
717170003 - Conditional Unfavorable
717170007 - No Objection
717170008 - Waiver of Recommendation

**Comment by godfreyyeung** [comment]
Summarizing discussion with @Eabrante :
In the future it would be ideal for us to get the same code-label mappings across all three participant types. E.g. 717170002 is "Unfavorable" for all participants. However, since our frontend code already handles different mappings,  for now it is simpler for us to to simply plug in the mappings as they are above.

When we (or the vendor) do standardize the mappings across participant types, we will also remove our frontend code that handles the different mappings.

**Comment by godfreyyeung** [comment]
Although the zap-staging postgres is still returning outdated data, upon inspecting zap-staging, the new frontend logic is responding to manually inserted updated values.
![image](https://user-images.githubusercontent.com/3311663/77720845-79231380-6fbf-11ea-929a-72d73176f39c.png)
![image](https://user-images.githubusercontent.com/3311663/77720857-82ac7b80-6fbf-11ea-9189-1653ba122cbf.png)
![image](https://user-images.githubusercontent.com/3311663/77720865-8a6c2000-6fbf-11ea-9ce5-c11d4f0b6111.png)

For example, if I assign "Favorable" to a Dispositions, dcp_communityboardrecommendation field, the associated assignment on the "Review" tab will show a "thumbs up". For "Waiver of Recommendation" it shows a gray comment bubble. For "conditional unfavorable" it shows a thumbs down, etc. 
(For "Approved", an invalid value, it shows no icon) 
![image](https://user-images.githubusercontent.com/3311663/77720894-9ce65980-6fbf-11ea-869b-af5c39f5f0fc.png)

That said, QA team still needs to test the recommendation submission. 
They should be able to do this since recommendations are directly submitted to CRM.
