### ISSUE TITLE
Some project addresses aren't loading even though the validated address fields are populated in ZAP

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-search#1141]
@hannahkates commented on [Mon Sep 10 2018](https://github.com/NYCPlanning/labs-zap-api/issues/56)

---

@hannahkates commented on [Thu Sep 13 2018](https://github.com/NYCPlanning/labs-zap-api/issues/56#issuecomment-421075814)

Examples to check: 
dcp_name = 'P2015K0393', dcp_projectid = '69bd16f5-1733-e811-812a-1458d04d06c8'
dcp_name = 'P2013Q0277', dcp_projectid = '2f683ec8-1733-e811-8129-1458d04d2538'

**Comment by hannahkates** [comment]
Closing - The UX for this is potentially confusing because sometimes the project brief sometimes includes an address, but other times it doesn't. The text match search looks for keywords, so sometimes an address keyword will work. Nothing is broken, but it is a confusing UX we should revisit in the future.
