### ISSUE TITLE
Staging: Reviewed tab is not displaying all of submitted recommendations/projects 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#1194]
Browser: Chrome
Project name:  1776 48th street Rezoning 

Expected Result: The Reviewed tab should display all of the reviewed projects 
Actual Result: The Reviewed tab is not displaying all of the reviewed projects, for my project, listed above, I submitted multiple recommendations manually and was successful in doing so, but the project record did not show up under the reviewed tab after submission 

The Project record on the CRM Side reflects the information that was submitted 

![image](https://user-images.githubusercontent.com/57362229/77943033-8cb5cf00-728a-11ea-8571-1f15f2f08055.png)

![image](https://user-images.githubusercontent.com/57362229/77943074-9d664500-728a-11ea-888d-010db1c608d5.png)

**Comment by hannahkates** [comment]
@ksinghprod Thanks - How long have you been waiting so far? I'm wondering if this may be ETL lag problem.

**Comment by ksinghprod** [comment]
@hannahkates I waited for more than an hour, Liz also has the same issue

**Comment by hannahkates** [comment]
Closing. TLDR: it's a human business logic issue, not a real bug. Long explanation provided below.

The missing project only has a Borough Board (BB) role assigned, not a Borough President (BP) role. In real life, there would never be a project with only a BB assignment and not a BP assignment. Both roles would be assigned to the same user, the BP. Our API uses deduping logic, so that the BP won't see confusing, duplicate info depending on the tab they're looking at. On the "upcoming" and "to review" tabs, the BP will see the project twice, because there are activities they can conduct in each of the two roles (scheduling hearings for each responsibility, etc). Once the project reaches the "Reviewed" and "Archive" tabs, we drop the BB assignment and only show the BP assignment, since there is no more action required. This way they only see the project once on those tabs.
