### ISSUE TITLE
Research Spike: Suprsend

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/labs-zap-search#1534]
This Issue is a research spike to evaluate [SuprSend](https://www.suprsend.com/) as the notification vendor to use for the ZAP Listserv project.

## Goals
* Assess documentation and try out product to determine if vendor's features meet requirements for the project
* Assess vendor developer documentation and report back on completeness and develop experience
* Document pricing model for vendor at various service tiers

High-level user stories for the project can be found in Figma [here](https://www.figma.com/design/1HrOm1tkJ3lowQhrSRkPLs/ZAP-Listserv%3A-Wireframes-and-User-Stories?node-id=232-11&t=ObwWGRg5ITae8cEt-0).

### Research questions
In addition to the user stories, here are some specific questions to answer in your research:
* How does this product allow users to sign up for notifications about some events but not others? We want to give users the option to sign up for updates on projects in any combination of community districts and/or citywide. What feature from the vendor supports this use case?
* Does the vendor support SMS (texting) as well as email?
* Does it automatically support sending users confirmation emails before actually subscribing them or is that something we would have to implement ourselves?
* Does the product have the concept of a staging (aka "test" or "dev") environment baked in? If not, how would we accomplish that?
* How does the vendor allow users to unsubscribe from notifications? Does it give users a web page they can visit to manage their subscriptions or only simple "unsubscribe" links in the individual emails?
* What analytics/observability features does the product offer? Does it show us how often our notifications are actually being open and read?
* How does templating for emails work? Does the product offer a built-in template builder? Does it allow us to format the emails in code, such as with a templating language like Handlebars?
* Does the product support "batching" or "digests"? We may want to send notifications to their API in real time but have the notifications be aggregated and sent to users on a set schedule, such as daily.
* We may want to let users subscribe to get notifications on a different schedules. For example, a user could get an email either daily or weekly with all of the notifications since the last email. Does the product support that out of the box?
* What security/compliance accreditations does the vendor have? Such as:
    * SOC II
    * FedRamp
    * ISO 27001

#### Notes
The engineer taking this on is encouraged to create a free account with the vendor if a free tier is offered and play around. You're also encouraged to reach out to the vendor to schedule a demo. Please CC @TylerMatteo on all comms with vendors.

#### Deliverables
The developer taking this on should document answers to these questions as well as their overall impression of the vendor. Documentation can be put in comments to this Issue or a GH Discussion to be linked to in a comment below.

AE will be presenting this research at Technical Design Review on 8/26. @TylerMatteo will follow up with details on how to incorporate research into the slide deck mid-sprint.

**Comment by pratishta** [comment]
### WIP

- How does this product allow users to sign up for notifications about some events but not others? We want to give users the option to sign up for updates on projects in any combination of community districts and/or citywide. What feature from the vendor supports this use case? 
- Does the vendor support SMS (texting) as well as email? **Yes, SuprSend calls 3rd party integrations vendors and they have [multiple options for SMS](https://docs.suprsend.com/docs/sms-vendor-integration)**
- Does it automatically support sending users confirmation emails before actually subscribing them or is that something we would have to implement ourselves?
- Does the product have the concept of a staging (aka "test" or "dev") environment baked in? If not, how would we accomplish that?
- How does the vendor allow users to unsubscribe from notifications? Does it give users a web page they can visit to manage their subscriptions or only simple "unsubscribe" links in the individual emails?
- What analytics/observability features does the product offer? Does it show us how often our notifications are actually being open and read?
- How does templating for emails work? Does the product offer a built-in template builder? Does it allow us to format the emails in code, such as with a templating language like Handlebars? **Has a [robust templating system](https://docs.suprsend.com/docs/email), there is a template builder that can be used entirely without code. Includes [documentation for handlebars helpers](https://docs.suprsend.com/docs/handlebars-helpers)** 
- Does the product support "batching" or "digests"? We may want to send notifications to their API in real time but have the notifications be aggregated and sent to users on a set schedule, such as daily. **[Yes](https://docs.suprsend.com/docs/batch) it's possible to add this as a "node" to the notification workflow we create**
- We may want to let users subscribe to get notifications on a different schedules. For example, a user could get an email either daily or weekly with all of the notifications since the last email. **Does the product support that out of the box? Yes with [dynamic batch window](https://docs.suprsend.com/docs/batch#dynamic-batch-window)**
- What security/compliance accreditations does the vendor have? Such as:
- SOC II
- FedRamp
- ISO 27001

**Comment by pratishta** [comment]
[Pricing](https://www.suprsend.com/pricing) 

Notes:

- Both Free and Growth ($99/month for 25k notifications) plans don't allow notification preferences which we might want for users to be able to get individual district level notifications 
- Seems like we'd need to call to set up custom pricing which would give us the features we'd want
