### ISSUE TITLE
Users want a new tab to open when clicking on project

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-zap-search#431]
Right now users will oftentimes lose their place on the list view because clicking on a project does not open in another tab. Opening project in another tab also means the coordinates and zoom level on the map will persist.

**Comment by hannahkates** [comment]
This could be the best solution to #331.

**Comment by andycochran** [comment]
@hannahkates I don't understand how this is related to 331? 

Another fix would be to persist the filters and map zoom in the app so that when users go back to the map it's as they left it. UX best practices often say that forcing the user to open projects in a new tabs is… taboo 🥁. Users currently _can_ open projects in a new tab; that's a browser feature.

**Comment by andycochran** [comment]
I think the story should be change from "Users want a new tab to open when clicking on project" to "Users want their filters and map state to persist when navigating to/from projects."
