### ISSUE TITLE
Frontend: User can upload document on recommendation form UI.

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#543]
PURSUE PATH OF LEAST RESISTANCE!

**Comment by allthesignals** [comment]
![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/59549448-a3a8-4766-a455-45d746bb6f38)

Through the UI this needs to send new data to the database...

**Comment by godfreyyeung** [comment]
We'll soon need to make more design decisions on this:

- Can users select one or multiple files to upload at a time? (I'm leaning towards one)
- Will each file upload immediately, or after user clicks "submit" on the confirmation modal? (I'm leaning towards after "submit").
- If upload occurs after "submit", will we prevent disposition submission if file upload(s) fail?
- We'll need some UI visuals for waiting for file upload.

Thoughts @andycochran @allthesignals @hannahkates

**Comment by andycochran** [comment]
I agree that upload should happen upon submit, not upon selection. We could add an "uploading" route that waits for a response and redirects to `/recommendations/done` upon success. (I can create a `/recommendations/uploading` view with a message and spinner icon.)

If upload fails, we should prevent submission of the disposition and redirect back to `recommendations/add` with a message at the top to try again. (Because if the dispositions are submitted, there'd be no way to try again.) 

Why are you leaning towards selecting one file at a time? Is there a technical reason? If we're uploading them all at once, what would be the reason to select them one at a time? 

We probably need UI to remove mistakenly selected files — e.g. a red × next to each selected file. Otherwise there's no way to cancel an upload without refreshing and redoing the whole form. 

For the technical Q, we'll need to confirm w/ an SME (Aline or David?) whether the documents are attached to all or one disposition.

**Comment by godfreyyeung** [comment]
@andycochran Okay, sounds good on "upload on submit" and the `/recommendations/uploading` route! 

Now that I think about it again, I agree it doesn't make sense to restrict users to selecting one file at a time. I think I was muddling the UI design with the implementation detail of only being able to POST one file at a time. (But we can just make multiple file upload POST requests). 

The UI to remove files is possible! 

Alright, maybe we can get confirmation from them at an upcoming standup.

**Comment by andycochran** [comment]
@godfreyyeung, we got a bit of clarity on how the files should be associated with multiple dispositions. Tho @hannahkates and I need to 100% confirm this: 

- When the user submits one recommendation for multiple actions, a copy of the uploaded file should be added to the Sharepoint folder for each action.

- When the user submits multiple recommendations for each action separately, the file should be associated only with one particular action. 

This means that the form should be updated so that there's a file upload UI for each action. It also means that when we display uploaded files in the public view, we'll need to de-dupe them if the user submits one recommendation.

**Comment by andycochran** [comment]
^ This is confirmed.

**Comment by allthesignals** [comment]
https://dcppfsuat2.crm9.dynamics.com/api/data/v9.1/EntityDefinitions(LogicalName='dcp_communityboarddisposition')/Attributes(8866e45f-2e5f-48a2-9c8a-04727655b982)/Microsoft.Dynamics.CRM.PicklistAttributeMetadata?$select=LogicalName&$expand=OptionSet($select=Options),GlobalOptionSet($select=Options)
