### ISSUE TITLE
Integrate NYC.ID login

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#544]
This will be used by both LUPs (govt employee district managers) and members of the public who will use their personal emails. 

NYC.ID Manual: https://www1.nyc.gov/assets/nyc4d/html/services-nycid/is-nycid-for-you.shtml

To get a testing account, you need to ask DoITT (form is included in the manual ^) to let your DCP account access the nyc.id non production console where you can create service account for your application.

1. Get access
2. Add login button in the header
3. Create route for nyc.id login
4. Redirect back

**Comment by allthesignals** [comment]
@andycochran followed up with @hadekoyaDCP about pinging DoiTT on the access request

**Comment by allthesignals** [comment]
DoiTT should have the provisioning done by the end of the day

**Comment by allthesignals** [comment]
Judging from what I've learned from CD Needs, we can just get away with using OAuth and avoid a more complicated SAML-based implementation.

The FE app should able to start with logging in this way: https://github.com/simplabs/ember-simple-auth. 

This will probably have to be handled by the API in the end, however, in order to authorize certain user actions against Project records.

**Comment by hadekoyaDCP** [comment]
Hi Matt - wanted to flag that the oath vs saml comes with some limitations... as Chengying pointed out social media login cannot be removed from oath implementations. Also limited on how much you can customize landing page...

HASSAN ADEKOYA
CHIEF INFORMATION OFFICER | IT DIVISION

NYC DEPT. OF CITY PLANNING
120 BROADWAY, 30<x-apple-data-detectors://1/0>st<x-apple-data-detectors://1/0> FLOOR<x-apple-data-detectors://1/0> • <x-apple-data-detectors://1/0> NEW YORK, NY 10271<x-apple-data-detectors://1/0>
212-720-3551<tel:212-720-3551> I hadekoya@planning.nyc.gov<mailto:hadekoya@planning.nyc.gov>

Sent from my mobile device. Please pardon any typos.

On Aug 1, 2019, at 5:26 PM, Matt Gardner <notifications@github.com<mailto:notifications@github.com>> wrote:


Judging from what I've learned from CD Needs, we can just get away with using OAuth and avoid a more complicated SAML-based implementation.

The FE app should able to start with logging in this way: https://github.com/simplabs/ember-simple-auth.

This will probably have to be handled by the API in the end, however, in order to authorize certain user actions against Project records.

**Comment by hadekoyaDCP** [comment]
Hi! Thanks — it seems like a SAML-based implementation gives you access to more NYC.ID features, but I think we might not need all those, and can settle for the simpler-but-limited oauth approach. I’m not sure I understand why social media login would matter here, but maybe I’m missing some context? Would love to chat more in person if it helps me better understand how to approach this integration…

Also, Chengying was super helpful and provided the CD Needs source code 😊 so thanks for that!

Matt

From: "Hassan Adekoya (DCP)" <HAdekoya@planning.nyc.gov>
Date: Thursday, August 1, 2019 at 7:02 PM
To: NYCPlanning/labs-zap-search <reply@reply.github.com>
Cc: NYCPlanning/labs-zap-search <labs-zap-search@noreply.github.com>, Mention <mention@noreply.github.com>, "William (Matt) Gardner (DCP)" <WGardner@planning.nyc.gov>, "LABS_DL (DCP)" <LABS_DL@planning.nyc.gov>, "Chengying He (DCP)" <che@planning.nyc.gov>
Subject: Re: [NYCPlanning/labs-zap-search] Integrate NYC.ID login (#544)

Hi Matt - wanted to flag that the oath vs saml comes with some limitations... as Chengying pointed out social media login cannot be removed from oath implementations. Also limited on how much you can customize landing page...
HASSAN ADEKOYA
CHIEF INFORMATION OFFICER | IT DIVISION

NYC DEPT. OF CITY PLANNING
120 BROADWAY, 30<x-apple-data-detectors://1/0>st<x-apple-data-detectors://1/0> FLOOR<x-apple-data-detectors://1/0> • <x-apple-data-detectors://1/0> NEW YORK, NY 10271<x-apple-data-detectors://1/0>
212-720-3551<tel:212-720-3551> I hadekoya@planning.nyc.gov<mailto:hadekoya@planning.nyc.gov>

Sent from my mobile device. Please pardon any typos.

On Aug 1, 2019, at 5:26 PM, Matt Gardner <notifications@github.com<mailto:notifications@github.com>> wrote:

Judging from what I've learned from CD Needs, we can just get away with using OAuth and avoid a more complicated SAML-based implementation.

The FE app should able to start with logging in this way: https://github.com/simplabs/ember-simple-auth.

This will probably have to be handled by the API in the end, however, in order to authorize certain user actions against Project records.

**Comment by hadekoyaDCP** [comment]
Hi,

Just share some difference between nyc.id OAuth and SAML provider. With OAuth, your login page will be look like this one<https://www1.nyc.gov/account/login.htm?spName=www1.nyc.gov-account&samlContext=e313b16e-1e7b-4311-8679-dbdab005da5a>. With SAML, you can remove some Login options on the right or completely customize the page like this <https://passport.cityofnewyork.us/page.aspx/en/usr/login?ReturnUrl=%2fpage.aspx%2fen%2fbuy%2fhome> .
[cid:image001.jpg@01D54943.F534EAA0]

Matt, no problem. Let me know if you need any addition information.

Best,

Chengying

**Comment by allthesignals** [comment]
@hannahkates 

A remaining touchpoint with DoiTT will be getting `planninglabs.nyc` [authorized for redirect](https://www1.nyc.gov/assets/nyc4d/html/services-nycid/mobile.shtml#overview), since that's what we use for staging:

> The URI that the user is sent to after completing the authorization process. The "redirect_uri" must be registered and have a domain name of doitt.nycnet, nyc.gov, nycid.nycnet, csc.nycnet, cloudapp.net, hpd.nycnet, nycgovparks.org, finance.nycnet, hpdnyc.org, cs.nycnet, gcomsoft.com, records.nycnet, dcas.nycnet, dhs.nycnet, redcapcloud.com, cityofnewyork.us, dynamics.com, dynamics365portals.us, getinfo.nyc, fdnycloud.org, microsoftonline.com, mkscloud.com, samaritan.com, ivalua.us, sbs.nycnet, communityneeds.nyc, ukrosoft.com.ua, appgeo.com, azurewebsites.net, or gigya.com. Please contact nycidintegration@doitt.nyc.gov to add your domain name to the list of valid domains.

@hadekoyaDCP we might need sign-off from you or something — should I handle the initial engagement?

**Comment by allthesignals** [comment]
I sent an e-mail to nycidintegration about this, cc'd the team
