### ISSUE TITLE
Show multiple votes on project listing

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#617]
How should we display multiple votes per LUP on the project record in the project listing? Should we have multiple thumb icons, one per recommendation?

**Comment by andycochran** [comment]
https://docs.google.com/drawings/d/1NNVpeI7wFMOFDx7bLgvM2dwNUPHP2mBQG7rzxg8jp3k/edit?usp=sharing

**Comment by hannahkates** [comment]
Per demo feedback, the thumb emojis should be solid green or red.

**Comment by allthesignals** [comment]
This is ready to build

**Comment by allthesignals** [comment]
![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/87838e0e-5329-4139-83a3-ec0e1eafcb65)

Votes should come from the "milestone outcome" property, which is provided on the project. This may need to be a new model but we could probably just get away with an array of objects since it's read-only view logic.

**Comment by andycochran** [comment]
#723 has some markup for showing votes. See updated [wireframes](https://docs.google.com/drawings/d/1NNVpeI7wFMOFDx7bLgvM2dwNUPHP2mBQG7rzxg8jp3k/edit):

![image](https://user-images.githubusercontent.com/409279/65791303-6ffbdb80-e12f-11e9-9f4b-76b0179bc279.png)
