### ISSUE TITLE
API needs to provide assignements endpoint so buttons can reflect LUP user role

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#714]
In two different places in the app, the buttons are hardcoded to say "Community Board". We need to dynamically render participant type labels in templates based on `project.teammemberrole` to display the correct LUP role. 
- [ ] "To review" tab (this will also soon be similar on the "upcoming" tab) https://github.com/NYCPlanning/labs-zap-search/blob/develop/app/templates/components/to-review-project-card.hbs#L54
- [ ] Project profile https://github.com/NYCPlanning/labs-zap-search/blob/develop/app/templates/show-project.hbs#L156
  - [x] On the project profile, we also need to provide the correct dates

**Comment by allthesignals** [comment]
Big issue: the LUP view currently shows a list of _projects_, but the particular query that produces that list is actually querying for _dispositions_. Because there are multiple roles, and because there are multiple dispositions held for a given project, there can be multiple projects in the list.

Ember needs to be querying for _dispositions_ rather than _projects_. The backend will need to be updated to provide a dispositions endpoint... 

@trbmcginnis @godfreyyeung let's figure out what needs to happen to fix this. I know this affects a lot of your work.

**Comment by allthesignals** [comment]
The LUP query as is provides something more along the lines of "Assignments" rather than either projects or dispositions.

This means we need a new model: assignments—along with a new endpoint.

An Assignment belongs to a project and belongs to a user and has many user-specific dispositions . 

The my-projects dashboard view should make a request for a collection of assignments. The views will reference the relevant project for that assignment. The links from those cards will link out to an _assignment_ and modify recs or hearings for that _assignments_ (plural!).

**Comment by godfreyyeung** [comment]
When we work on this PR, we should make sure to replaces references to `project.dcpLupteammemberrole` (or  `model.dcpLupteammemberrole` ) with  something like `project.assignments[0].dcpLupteammemberrole`. 
I.e. on `show-project.hbs` 

This is because by that time issues like #773 will be merged
