### ISSUE TITLE
Add guards against undefined values passed into `{{moment-format}}`

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-zap-search#823]
Otherwise, moment-format shows the current date.

**Comment by allthesignals** [comment]
We might consider putting this in the moment and having a computed for formatted date handling? IDK if it makes sense to have that in the model since they're only used in views, but in the absence of something like a [presenter pattern](https://nithinbekal.com/posts/rails-presenters/) it might be the best approach. Thoughts?

**Comment by godfreyyeung** [comment]
@allthesignals The presenter pattern is super neat and that article was fantastic. Thanks for referencing that!  

Right now the `assignment` model has a five computed that return unhandled dates, so would we need to create five corresponding CPs just for the formatted version of those dates?

Currently thinking of creating a component for app-wide date handling

**Comment by hannahkates** [comment]
In these cases, we should return "Date Unknown" instead
