### ISSUE TITLE
Upcoming milestone timeline display issues

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#869]
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/c96d3fbf-7b54-4bd9-88a1-a078a9e5fcd1)

**Comment by andycochran** [comment]
If I'm understanding the logic for this code, it's showing: 
- the first milestone
- "VIEW FULL TIMELINE" link
- the last completed milestone
- all milestones after the last completed milestone

And since the last completed milestone can be the first milestone, the first milestone can show up twice in the list. 

Would it make sense to instead show explicit milestones this? 
- the first completed milestone
- "VIEW FULL TIMELINE" link
- the 4 milestones that are specifically part of the public review process
  - "Application Reviewed at City Planning Commission Review Session"
  - "Community Board Review"
  - "Borough Board Review"
  - "Borough President Review"
