### ISSUE TITLE
Projects with geoms are showing up as "Not Mapped"

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-zap-search#872]
The two Gowanus projects have geometries, but the "Not Mapped" indicator is being falsely triggered on staging.

Update: all projects are showing as "Not Mapped"

![image](https://user-images.githubusercontent.com/13967925/67954850-00628b80-fbc8-11e9-9505-b0d2df83e2c6.png)

**Comment by andycochran** [comment]
This might just be an unintended regression. 

This is a result of https://github.com/NYCPlanning/labs-zap-search/commit/edd346dabd4f1e604ef141959301e140ae2da6e0#diff-30001b151337f8a9f1a04b146d31855cR3-R10 ("Fix prop names") which comments out the `{{project-list-map-pin}}` component. 

The component was also later deleted in https://github.com/NYCPlanning/labs-zap-search/commit/2d44735fe7ad03f13212c6e6e944edd1bad3245f ("Remove unused components and models"). 

The comment says, "commented out because it was if-gated by .has_centroid which no longer exists" but I do see `"has-centroid": true,` in the [API response](https://zap-api.herokuapp.com/projects?dcp_publicstatus%5B%5D=Filed&page=1). 

![image](https://user-images.githubusercontent.com/409279/68415513-88b0d580-0160-11ea-8e24-d63d03b18468.png)

@allthesignals, can I simply undo those two changes — re-add the `{{project-list-map-pin}}` component and put the if back? 

I'm not sure how to work on this without using real API data locally.

**Comment by allthesignals** [comment]
@andycochran yeah why not? have you tried it?

**Comment by andycochran** [comment]
I tried/failed to get the API running locally so I could see real data.

**Comment by allthesignals** [comment]
Why do you need to run the API locally for this? Your screenshot shows the API is already providing this. You could run the Ember app to point to the staging/production API and check it out that way, too.
