### ISSUE TITLE
Selecting PM w/o clicking breaks validation/modal

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zap-search#885]
To replicate… 
- Go to `…/hearing/add`
- Click yes
- Click location input, enter text
- Click date input, select date
- Click hour input, type a number
- Click minute input, type a number
- Tab to AM/PM input (don't click)
- Type a "p" to select PM
- Click "Continue" button
- Nothing happens — the form does not validate, the modal does not open

**Comment by trbmcginnis** [comment]
This is because it is actually the click event that saves the value to the controller. There are also some calculations that depend on PM/AM selection to calculate a date&time. If these date&time values are not valid, a user cannot continue. I will disable typing in the box and just make it so that a user can only select one of the two options

**Comment by trbmcginnis** [comment]
This is a weird `power-select` thing -- there are two actions associated with this power-select. `onChange` modifies a local variable `this.timeOfDay` and `onClose` runs the action `setHearingDate`. AM/PM information is necessary to calculate a final date so after saving it locally it's using again to produce `dcpDateofpublichearing`

When a user just types in `P`, no "closing" of the power-select happens, so that action does not run. Going to try to disable this typing so that a user has to select by clicking
