### ISSUE TITLE
User can get back to filter view from project view

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-zap-search#92]

**Comment by chriswhong** [comment]
The user can use the back button to go back to the filter view from the project view, but maybe we should consider adding a "back to project list" (or whatever)  button with icon near the top of the page.

**Comment by allthesignals** [comment]
What satisfies this - adding an explicit back button? "See results"?

**Comment by andycochran** [comment]
If this is a "back to results" button in the Project view, the project will need to be aware of the HTTP Referer or the previous route and show this button conditionally. 

If you land on this page, a "back to" link makes no sense. There should be a search/filter link in the site header for these users. Maybe this header link also knows about your last search/filter results and preserves them?

However. if the back button does exactly what this issue is describing, I say we table this idea and do user testing to see if folks have trouble getting back to their search results.

**Comment by chriswhong** [comment]
For now, let's add a 'Find Applications' link to the header that takes you to the filter page
