### ISSUE TITLE
The LUP portal displays a disposition record that has been deactivated  

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#935]
Browser: Chrome 
Project ID: 130-24 South Conduit Ave Self Storage 

Expected Result: Inactive dispositions records should not show up on the LUP portal
Actual Result: Inactive Disposition record is displaying on the LUP portal, for the LUP team member has been deactivated from the project (from CRM)

Side note: When we deactivate a lup team member from CRM, his/her disposition records become inactive.

(I waited 14 minutes to see if the public hearing record disappears from the Portal, but it did not)

**Comment by gopal2020** [comment]
Triage: Inactive records that are "deactivated" as status reason should not ever be displayed, all other inactive records should display but as read-only (not editable).
QA to to confirm that deactivation of LUP team changes associated disposition record status reason to 'deactivated', if not MCS bug.

**Comment by hannahkates** [comment]
This doesn't seem to be an issue anymore with the newly cloned data from production. "130-24 South Conduit Ave Self Storage" is no longer appearing in the results for QN BP. My guess is that it was a temporary data issue.

**Comment by ksinghprod** [comment]
This issue is still present, I deactivated a hearing from CRM however, the information for the hearing is still appearing on the portal. 
(I waited about 25 minutes)

![image](https://user-images.githubusercontent.com/57362229/69983146-feac2080-1503-11ea-980e-f116a9ae5b27.png)

**Comment by hannahkates** [comment]
Our database has two disposition records that have not been deactivated. One is "saved" the other is "submitted"

![image](https://user-images.githubusercontent.com/13967925/70001730-0d0e3280-152c-11ea-881f-b3b118eb378b.png)

If you change the filter in CRM to show "All Project Dispositions" instead of "Project Disposition Associated View" the two dispositions both show up there too. It seems like the "Gopal's desk" one wasn't actually deactivated; it was submitted.

![image](https://user-images.githubusercontent.com/13967925/70001915-860d8a00-152c-11ea-8ce7-f3c6586503c8.png)

**Comment by ksinghprod** [comment]
here you are @allthesignals ![image](https://user-images.githubusercontent.com/57362229/70067268-05966a00-15bc-11ea-83ae-d3c17b30beed.png)

**Comment by hannahkates** [comment]
@ksinghprod I'm not finding a deactivated disposition record in CRM or our database. Are you sure it's deactivated?

![image](https://user-images.githubusercontent.com/13967925/70071377-4940a200-15c3-11ea-84c9-1ef5c9fff120.png)

**Comment by ksinghprod** [comment]
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/70074163-2c5a9d80-15c8-11ea-832c-ec9ac234584c.png)
