### ISSUE TITLE
Stage: In progress Community Board milestone Disposition displaying under Upcoming List

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#999]
Project Name :  180-186 Throop AVE FRESH Certification 

Actual Result: In progress Community Board milestone Disposition displaying under Upcoming List.
Expected Result: In progress Community Board milestone Disposition should display under To Review List

![image](https://user-images.githubusercontent.com/57265341/69452084-e3385d00-0d2e-11ea-83d6-a4ec4bda81e0.png)

![image](https://user-images.githubusercontent.com/57265341/69452022-bedc8080-0d2e-11ea-9f38-bc79b4b0ec80.png)

**Comment by hannahkates** [comment]
I think there's something wrong with this specific CB review milestone. In CRM it says "in progress" but in our SQL database it says it's still "not started". I wonder if it has something to do with the fact that the milestone doesn't have lead action in the name, so maybe it's not registering properly in the system. It's called "- Community Board Referral" instead of "ZC - Community Board Referral"

**Comment by hannahkates** [comment]
This was a data update issue and it is no longer a problem.

**Comment by ksinghprod** [comment]
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/70087921-32aa4300-15e3-11ea-8577-3401f2117e8a.png)
